"""
agent/sar_generator.py
──────────────────────
Regulatory Suspicious Activity Report (SAR) generation.
Produces FinCEN-compliant SAR drafts using the LLM,
structured as per 31 U.S.C. § 5318(g) requirements.
"""
from __future__ import annotations

import json
from datetime import datetime
from typing import Any, Dict, Optional

from agent.state import (
    ActionRecommendation,
    AuditEvent,
    FraudAgentState,
    GraphEvidence,
    RiskAssessment,
)


# ─── SAR Template Fields (FinCEN Form 111) ────────────────────────────────────

SAR_TEMPLATE = """
SUSPICIOUS ACTIVITY REPORT (SAR)
FinCEN Form 111 — Automated Draft

═══════════════════════════════════════════════════════════════

PART I — FILING INSTITUTION INFORMATION
────────────────────────────────────────
Filing Institution:  HHGOA National Bank (Demo)
LEI:                 [LEI-PLACEHOLDER]
Contact Name:        Fraud Investigation System (AI-Generated Draft)
Contact Phone:       +1-800-FRAUD-00
Filing Date:         {filing_date}
SAR Reference ID:    {sar_ref_id}

═══════════════════════════════════════════════════════════════

PART II — SUBJECT INFORMATION
────────────────────────────────────────
Subject Account ID:  {account_id}
Case Reference:      {case_id}
Activity Period:     {activity_start} to {activity_end}
Suspicious Amount:   ${amount:,.2f} USD

═══════════════════════════════════════════════════════════════

PART III — SUSPICIOUS ACTIVITY INFORMATION
────────────────────────────────────────
Fraud Typology:       {fraud_typology}
Risk Score:           {risk_score:.2f} / 1.00
Fraud Probability:    {fraud_probability:.0%}
Uncertainty Score:    {uncertainty_score:.0%}

Activity Category:    {activity_category}
Suspicious Indicators:
{suspicious_indicators}

═══════════════════════════════════════════════════════════════

PART IV — GRAPH EVIDENCE SUMMARY
────────────────────────────────────────
Shared Device Accounts:   {shared_device_count}
Shared IP Accounts:       {shared_ip_count}
IP Proxy Detected:        {ip_proxy}
New Device Detected:      {new_device}
Velocity Burst Score:     {velocity:.2f}
Fraud Ring Size:          {ring_size}
Subgraph Path:            {subgraph_path}

═══════════════════════════════════════════════════════════════

PART V — NARRATIVE
────────────────────────────────────────
{narrative}

═══════════════════════════════════════════════════════════════

PART VI — LAW ENFORCEMENT CONTACT
────────────────────────────────────────
If this SAR relates to an ongoing criminal investigation, please
contact the relevant law enforcement agency with this reference:
SAR-REF: {sar_ref_id}

NOTE: This SAR was auto-generated by the HHGOA Fraud Investigation
Agent and requires review and sign-off by a Compliance Officer
before submission to FinCEN.

REQUIRED APPROVAL: COMPLIANCE_OFFICER
FILING DEADLINE:   Within 30 days of detection ({filing_date})
REGULATORY BASIS:  31 U.S.C. § 5318(g) | 31 CFR § 1020.320
═══════════════════════════════════════════════════════════════
"""

TYPOLOGY_ACTIVITY_CATEGORIES = {
    "CARD_NOT_PRESENT_RING":  "Credit Card Fraud / Identity Theft",
    "ACCOUNT_TAKEOVER":       "Account Takeover / Unauthorized Access",
    "BUST_OUT":               "Bust-Out / Credit Abuse",
    "SYNTHETIC_IDENTITY":     "Synthetic Identity Fraud",
    "SMURFING_VELOCITY":      "Structuring / Money Laundering",
    "UNKNOWN":                "Suspicious Activity (Unclassified)",
}


def _build_suspicious_indicators(
    risk: RiskAssessment,
    evidence: GraphEvidence,
) -> str:
    """Bullet-list the key suspicious signals."""
    indicators = []

    if evidence.ip_proxy_detected:
        indicators.append("• IP address identified as proxy/VPN — obfuscated geographic origin")
    if evidence.new_device_detected:
        indicators.append("• Transaction initiated from device not previously associated with account")
    if evidence.shared_device_accounts:
        indicators.append(
            f"• Device shared across {len(evidence.shared_device_accounts)} unrelated accounts "
            f"(IDs: {', '.join(evidence.shared_device_accounts[:5])})"
        )
    if evidence.shared_ip_accounts:
        indicators.append(
            f"• IP address shared across {len(evidence.shared_ip_accounts)} accounts"
        )
    if evidence.velocity_burst_score > 5.0:
        indicators.append(
            f"• Velocity burst score {evidence.velocity_burst_score:.1f} — anomalous transaction rate"
        )
    if evidence.ring_size >= 3:
        indicators.append(
            f"• Fraud ring detected: {evidence.ring_size} accounts sharing credentials (component: {evidence.ring_component_id})"
        )
    for signal in risk.conflicting_signals:
        indicators.append(f"• Conflicting signal: {signal}")
    for factor in risk.confidence_factors[:5]:
        indicators.append(f"• Supporting evidence: {factor}")

    return "\n".join(indicators) if indicators else "• No specific indicators extracted."


def generate_sar_draft(
    state: FraudAgentState,
    narrative: Optional[str] = None,
) -> str:
    """
    Generate a structured SAR draft from the current investigation state.
    Uses either a provided narrative or auto-generates one from state.

    Args:
        state:     Current FraudAgentState.
        narrative: Optional pre-generated narrative (from LLM).

    Returns:
        Formatted SAR string ready for compliance review.
    """
    import uuid

    risk     = state.get("risk_assessment", RiskAssessment())
    evidence = state.get("graph_evidence", GraphEvidence())
    trigger  = state.get("trigger")
    post_act = state.get("post_evidence_action")

    account_id = state.get("account_id", "UNKNOWN")
    case_id    = state.get("case_id", "UNKNOWN")
    amount     = trigger.amount if trigger and hasattr(trigger, "amount") else 0.0

    typology     = risk.likely_fraud_type.value if hasattr(risk.likely_fraud_type, "value") else str(risk.likely_fraud_type)
    activity_cat = TYPOLOGY_ACTIVITY_CATEGORIES.get(typology, "Suspicious Activity")
    sar_ref      = f"SAR-{uuid.uuid4().hex[:10].upper()}"
    filing_date  = datetime.utcnow().strftime("%Y-%m-%d")

    # Auto-generate narrative if not supplied
    if not narrative:
        narrative = _auto_narrative(state, risk, evidence, typology, amount)

    indicators = _build_suspicious_indicators(risk, evidence)

    return SAR_TEMPLATE.format(
        filing_date          = filing_date,
        sar_ref_id           = sar_ref,
        account_id           = account_id,
        case_id              = case_id,
        activity_start       = filing_date,
        activity_end         = filing_date,
        amount               = amount,
        fraud_typology       = typology,
        risk_score           = risk.fraud_probability,
        fraud_probability    = risk.fraud_probability,
        uncertainty_score    = risk.uncertainty_score,
        activity_category    = activity_cat,
        suspicious_indicators = indicators,
        shared_device_count  = len(evidence.shared_device_accounts),
        shared_ip_count      = len(evidence.shared_ip_accounts),
        ip_proxy             = "YES" if evidence.ip_proxy_detected else "NO",
        new_device           = "YES" if evidence.new_device_detected else "NO",
        velocity             = evidence.velocity_burst_score,
        ring_size            = evidence.ring_size,
        subgraph_path        = evidence.subgraph_path_summary or "N/A",
        narrative            = narrative,
    )


def _auto_narrative(
    state: FraudAgentState,
    risk: RiskAssessment,
    evidence: GraphEvidence,
    typology: str,
    amount: float,
) -> str:
    """Generate a narrative without LLM for offline/demo mode."""
    case_id    = state.get("case_id", "UNKNOWN")
    account_id = state.get("account_id", "UNKNOWN")
    pre_act    = state.get("pre_evidence_action")
    addl_ev    = state.get("additional_evidence")
    post_act   = state.get("post_evidence_action")

    pre_action_str  = pre_act.action.value  if pre_act  else "N/A"
    addl_resp_str   = addl_ev.response_received if addl_ev else "N/A"
    post_action_str = post_act.action.value if post_act else "N/A"

    return f"""
On {datetime.utcnow().strftime('%Y-%m-%d')}, account {account_id} was flagged for suspicious activity
consistent with {typology} fraud pattern. The automated Fraud Investigation Agent (HHGOA System)
initiated Case {case_id} following a trigger event with an initial risk score of
{risk.fraud_probability:.2f} and uncertainty score of {risk.uncertainty_score:.2f}.

Graph analysis revealed the following structural anomalies:
{evidence.subgraph_path_summary or 'Multi-hop graph traversal identified shared identity connections.'}

Prior to requesting additional evidence, the agent recommended: {pre_action_str}.

Additional evidence was gathered via customer outreach. The customer response was: '{addl_resp_str}'.

Following evidence synthesis, the agent determined a final fraud probability of {risk.fraud_probability:.2f}
({risk.fraud_probability:.0%}) and recommended action: {post_action_str}.

Key risk factors included: {'; '.join(risk.confidence_factors[:3]) if risk.confidence_factors else 'elevated transaction velocity, shared infrastructure, and anomalous geographic patterns'}.

The total suspicious amount involved was ${amount:,.2f} USD.

This SAR is filed in compliance with 31 U.S.C. § 5318(g) and requires Compliance Officer review
prior to submission to FinCEN within the mandatory 30-day window.
""".strip()
